sudo: required
services:
  - docker

before_install:
  - docker build -t azegheru/docker-react -f Dockerfile.dev .

# Contains all the commands that need to be executed to run our test suite
script:
  - docker run -e CI=true azegheru/docker-react npm run test
