sudo: required
services:
  - docker

before_install:
  - docker build -t azegheru/docker-react -f Dockerfile.dev .

# Contains all the commands that need to be executed to run our test suite
script:
  - docker run -e CI=true azegheru/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-707777746658"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
